services:
  init:
    build: ./src/init
    image: frothwalker/init
    container_name: fw-init
    network_mode: host
    user: "root"
    restart: "no"
    environment:
      test: test
    volumes:
      - ./config.yaml:/data/config.yaml
      - nginx:/data/nginx
      - wireguard:/data/wireguard

  wireguard:
    build: ./src/wireguard
    image: frothwalker/wireguard
    container_name: fw-wireguard
    restart: always
    network_mode: host
    depends_on:
      init:
        condition: service_completed_successfully
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - IPC_LOCK
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    ports:
      - "51820:51820/udp"
    volumes:
      - wireguard:/data
    
  nginx:
    build: ./src/nginx
    image: frothwalker/nginx
    container_name: fw-nginx
    restart: always
    network_mode: host
    depends_on:
      init:
        condition: service_completed_successfully
    cap_add:
      - NET_ADMIN
    volumes:
      - nginx:/data

volumes:
  nginx:
  wireguard:
