services:
  init:
    build: ./src/init
    image: frothwalker/init
    container_name: fw-init
    network_mode: host
    user: "root"
    restart: "no"
    environment:
      test: test
    volumes:
      - ./config.yaml:/data/config.yaml
      - nginx:/data/nginx

#  wireguard:
#    build: ./src/wireguard
#    cap_add:
#      - NET_ADMIN
#    container_name: wireguard
#    stdin_open: true
#    tty: true
#    command: sleep infinity
    
  nginx:
    build: ./src/nginx
    image: frothwalker/nginx
    container_name: fw-nginx
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - nginx:/data

volumes:
  nginx:
  wireguard:
