# stream {
#     server {
#         listen 192.168.8.81:443;
#         proxy_pass 10.0.0.2:443;   # IP of backend Nginx reachable via WireGuard
#         proxy_timeout 10m;
#         proxy_connect_timeout 1s;
#     }
# }
# 
# server {
#     listen 443 ssl;
#     server_name service-a.example.com;
# 
#     ssl_certificate /etc/nginx/certs/service-a.crt;
#     ssl_certificate_key /etc/nginx/certs/service-a.key;
# 
#     location / {
#         proxy_pass http://app-service-a:8080;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     }
# }
     
server {
    listen 192.168.8.81:80;
    server_name _;

    location / {
        return 200 "ok 81\n";
    }
}

server {
    listen 192.168.8.82:80;
    server_name _;

    location / {
        return 200 "ok 82\n";
    }
}

